services:
  - type: web
    name: deepseek-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: HUGGINGFACE_API_KEY
        sync: false
    healthCheckPath: /health
